# Generated by Django 4.2 on 2023-04-27 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0002_months_nums_pronouns_rename_pronoun_days_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pronouns",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
