# Generated by Django 4.2 on 2023-04-27 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0005_family"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Family",
            new_name="Familys",
        ),
    ]
