# Generated by Django 4.2 on 2023-04-28 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0007_intros_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Months",
            new_name="Wh",
        ),
    ]
