# Generated by Django 4.2 on 2023-04-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0008_rename_months_wh"),
    ]

    operations = [
        migrations.AddField(
            model_name="days",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/intro/"),
        ),
        migrations.AddField(
            model_name="wh",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images/intro/"),
        ),
    ]
